# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcategory', models.CharField(max_length=31)),
                ('alias', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btag', models.CharField(max_length=31)),
                ('alias', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogtag',
            field=models.ManyToManyField(to='blog.BlogTags'),
        ),
    ]
